/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

#line 7 "strdup.c"
extern char* ( /* missing proto */  strdup)() ;
#line 8
extern int ( /* missing proto */  sparrow_print)() ;
#line 11
extern int ( /* missing proto */  printf)() ;
#line 5 "strdup.c"
int main(void) 
{ 
  char *a ;
  char *b ;
  char* tmp ;

  {
  {
#line 6
  a = (char *)"abcde";
#line 7
  tmp = strdup(a);
  sparrow_print(tmp);
#line 7
  b = (char *)tmp;
#line 8
  sparrow_print(a);
#line 9
  sparrow_print(b);
#line 11
  printf("a: %c\n", (int )*(a + 0));
#line 12
  printf("b: %c\n", (int )*(b + 0));
  }
#line 14
  return (0);
}
}
